server:
  port: 8081

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
spring:
  application:
    name: book-service
  config:
    import: "optional:configserver:"
  profiles:
    active: native
  data:
    mongodb:
      database: admin
      username: root
      password: root
