spring:
  cloud:
    config:
      enabled: false
      import-check.enabled: false

  application:
    name: book-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/my-mongo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
